version: '3.8'

services:
  web:
    build: ./web
    ports: 
      - "5173:5173"
    depends_on:
      - server

  app:
    build: ./app
    ports:
      - "65447:65447"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=Data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1234:5432"

volumes:
  pgdata:
        
